apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim1
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - image: k8s.gcr.io/dbtest:latest
        name: mysqldb
        env:
          # 在实际中使用 secret
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysqldb
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim1
---
apiVersion: v1
kind: Service  
metadata:
  name: mysqldb
spec:
  type: NodePort
  ports:
  - name: mysql-port 
    port: 3306
    nodePort: 32156
  selector:
    app: mysqldb

